### PR TITLE
feat: preview plain html file by HTML render first

### PR DESCRIPTION
**Pull request by jiz4oh**
image

By default, plain html file now rendered by **Markdown**, it would be easier to use if the **HTML render** as the first preview engine

image

image

### CODE REVIEW

**Comment by jiz4oh** [comment]
ci failed, but I believe it's not caused by this PR, also happend in https://github.com/alist-org/alist-web/pull/98/checks?check_run_id=15362762640

**Comment by jiz4oh** [comment]
Hi @Xhofe, could you look at this PR? A better default option is helpful

**Review by Xhofe — APPROVED** [review]

**Comment by jiz4oh** [comment]
@Xhofe thank you

**Comment by xhofe** [comment]
Thanks for your PR!

**Pull request merged**
