### PR TITLE
add 'OmniPlayer' and 'Fig Player ' to support players

### PR DESCRIPTION
**Pull request by waiwaib**

### CODE REVIEW

**Comment by xhofe** [comment]
Have you done a test?

**Comment by waiwaib** [comment]
yes. I did a simple test and the application had no change after I added the new content.  but when I access the application URL here always in  "Loading "  status as the attachments shows, is here any problem?  
1331700036815_ pic

**Comment by waiwaib** [comment]
> Have you done a test?

Yes. I did a simple test and the application had no change after I added the new content. but when I access the application URL here always in "Loading " status as the attachments shows, is here any problem?
1331700036815_ pic

**Comment by xhofe** [comment]
You need to run the backend server

**Comment by xhofe** [comment]
I'm just wondering where you got the schemes for these two apps as I can't find them with google.

**Comment by waiwaib** [comment]
> You need to run the backend server

got it. i haven't launch the backend.

**Comment by waiwaib** [comment]
> I'm just wondering where you got the schemes for these two apps as I can't find them with google.

 I am a member of the development team of these 2 players, omniplayer and figplayer are popular in mac app store.

**Comment by xhofe** [comment]
Got it, thanks for your contribution!

**Comment by waiwaib** [comment]
> Got it, thanks for your contribution!

Thanks!

**Pull request merged**
