### PR TITLE
fix: Incorrect current page of search paginator

### PR DESCRIPTION
**Pull request by itsHenry35**
before:
image

after:
image

### CODE REVIEW

**Review by xhofe — APPROVED** [review]

**Comment by itsHenry35** [comment]
@xhofe The "simplify code" needs to be reverted, your code still has an issue which my initial code didn't have
for example, if you search "a" and navigate to the sixth page, the result is correct for the "a" result's sixth page, however, when you  search "b", the paginator still shows 6 while the result for "b" is the first page. That's what this line of code was for: https://github.com/itsHenry35/alist-web/blob/1544f13f044f679bbd588f384a55bedcbc6e52c7/src/pages/home/folder/Search.tsx#L212
I think my code has already been the most simplified

**Comment by itsHenry35** [comment]
reproduction: 
image
image
image

**Comment by xhofe** [comment]
fine, I think we can make `Paginator` an optional controlled component, or give a reset callback

**Comment by itsHenry35** [comment]
> fine, I think we can make `Paginator` an optional controlled component, or give a reset callback

yeah but it's just not necessary because Show can be a way to reset the component

**Comment by itsHenry35** [comment]
> fine, I think we can make `Paginator` an optional controlled component, or give a reset callback

so now shall I create another PR to revert the commit or shall you implement a reset callback

**Comment by xhofe** [comment]
I prefer to implement a reset callback or make `Paginator` an optional controlled component

Using `Show` to reset components looks unorthodox

**Pull request merged**
